/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NigerianStockFactory } from "./NigerianStockFactory";
export type { NigerianStockToken } from "./NigerianStockToken";
