/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { NigerianStockFactory__factory } from "./NigerianStockFactory__factory";
export { NigerianStockToken__factory } from "./NigerianStockToken__factory";
